### ISSUE TITLE
request for real world example and explanaition

### ISSUE THREAD

**Issue by tavallaie** [BinDruid/django-cache-pydantic#4]
can you add some real world example and explanation for this package? it help to find in search and also shows when we should use it.

**Comment by aabharya** [comment]
> some real world example and explanation for this package? 

@tavallaie 
Basically any requirement that enforces some sort of validations on temporary states could lead you to use such utility packages.

The idea is streamlining the validation on cached instances. In some cases you want to create an actual django model instance from cached instances, so a unified ORM interface is plausible.
  
Here are some scenarios you could think about:

- Tracking Anonymous users

- Multi steps and wizard forms

- Sharing data between celery tasks
